package jh

//go:generate cpp -o jh_gen.go -P -undef -nostdinc -traditional -Wall jh.go -imacros $GOFILE
//go:generate gofmt -w jh_gen.go

const _ = `
#define build
#define ignore
#define HEAD_PLACEHOLDER Code generated by cpp. DO NOT EDIT.
`
