// Code generated by "stringer -type=NegotiateFlag"; DO NOT EDIT.

package ntlmssp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NTLMSSP_NEGOTIATE_UNICODE-1]
	_ = x[NTLM_NEGOTIATE_OEM-2]
	_ = x[NTLMSSP_REQUEST_TARGET-4]
	_ = x[NTLMSSP_NEGOTIATE_SIGN-16]
	_ = x[NTLMSSP_NEGOTIATE_SEAL-32]
	_ = x[NTLMSSP_NEGOTIATE_DATAGRAM-64]
	_ = x[NTLMSSP_NEGOTIATE_LM_KEY-128]
	_ = x[NTLMSSP_NEGOTIATE_NTLM-512]
	_ = x[NTLMSSP_ANONYMOUS_CONNECTIONS-2048]
	_ = x[NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED-4096]
	_ = x[NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED-8192]
	_ = x[NTLMSSP_NEGOTIATE_ALWAYS_SIGN-32768]
	_ = x[NTLMSSP_TARGET_TYPE_DOMAIN-65536]
	_ = x[NTLMSSP_TARGET_TYPE_SERVER-131072]
	_ = x[NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY-524288]
	_ = x[NTLMSSP_NEGOTIATE_IDENTIFY-1048576]
	_ = x[NTLMSSP_REQUEST_NON_NT_SESSION_KEY-4194304]
	_ = x[NTLMSSP_NEGOTIATE_TARGET_INFO-8388608]
	_ = x[NTLMSSP_NEGOTIATE_VERSION-33554432]
	_ = x[NTLMSSP_NEGOTIATE_128-536870912]
	_ = x[NTLMSSP_NEGOTIATE_KEY_EXCH-1073741824]
	_ = x[NTLMSSP_NEGOTIATE_56-2147483648]
}

const _NegotiateFlag_name = "NTLMSSP_NEGOTIATE_UNICODENTLM_NEGOTIATE_OEMNTLMSSP_REQUEST_TARGETNTLMSSP_NEGOTIATE_SIGNNTLMSSP_NEGOTIATE_SEALNTLMSSP_NEGOTIATE_DATAGRAMNTLMSSP_NEGOTIATE_LM_KEYNTLMSSP_NEGOTIATE_NTLMNTLMSSP_ANONYMOUS_CONNECTIONSNTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIEDNTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIEDNTLMSSP_NEGOTIATE_ALWAYS_SIGNNTLMSSP_TARGET_TYPE_DOMAINNTLMSSP_TARGET_TYPE_SERVERNTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITYNTLMSSP_NEGOTIATE_IDENTIFYNTLMSSP_REQUEST_NON_NT_SESSION_KEYNTLMSSP_NEGOTIATE_TARGET_INFONTLMSSP_NEGOTIATE_VERSIONNTLMSSP_NEGOTIATE_128NTLMSSP_NEGOTIATE_KEY_EXCHNTLMSSP_NEGOTIATE_56"

var _NegotiateFlag_map = map[NegotiateFlag]string{
	1:          _NegotiateFlag_name[0:25],
	2:          _NegotiateFlag_name[25:43],
	4:          _NegotiateFlag_name[43:65],
	16:         _NegotiateFlag_name[65:87],
	32:         _NegotiateFlag_name[87:109],
	64:         _NegotiateFlag_name[109:135],
	128:        _NegotiateFlag_name[135:159],
	512:        _NegotiateFlag_name[159:181],
	2048:       _NegotiateFlag_name[181:210],
	4096:       _NegotiateFlag_name[210:247],
	8192:       _NegotiateFlag_name[247:289],
	32768:      _NegotiateFlag_name[289:318],
	65536:      _NegotiateFlag_name[318:344],
	131072:     _NegotiateFlag_name[344:370],
	524288:     _NegotiateFlag_name[370:412],
	1048576:    _NegotiateFlag_name[412:438],
	4194304:    _NegotiateFlag_name[438:472],
	8388608:    _NegotiateFlag_name[472:501],
	33554432:   _NegotiateFlag_name[501:526],
	536870912:  _NegotiateFlag_name[526:547],
	1073741824: _NegotiateFlag_name[547:573],
	2147483648: _NegotiateFlag_name[573:593],
}

func (i NegotiateFlag) String() string {
	if str, ok := _NegotiateFlag_map[i]; ok {
		return str
	}
	return "NegotiateFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
