package groestl

//go:generate cpp -o groestl_gen.go -P -undef -nostdinc -traditional -Wall groestl.go -imacros $GOFILE
//go:generate gofmt -w groestl_gen.go

const _ = `
#define build
#define ignore
#define HEAD_PLACEHOLDER Code generated by cpp. DO NOT EDIT.
`
